import AppDataSource from './data-source';

// Records migrations whose effects are already in the schema (created by
// TYPEORM_SYNCHRONIZE) as applied, so `migration:run` only applies what's
// actually missing. Idempotent — safe to re-run:
//   npm run migration:baseline   (dev)
//   node dist/database/baseline.js   (prod image, from the app container)
const ALREADY_APPLIED: Array<{ timestamp: number; name: string }> = [
  // The role/banned columns are created by synchronize on every existing
  // deployment, so this pre-dates migration history.
  { timestamp: 1753000000000, name: 'AddUserRoleAndBanned1753000000000' },
];

async function baseline(): Promise<void> {
  await AppDataSource.initialize();
  try {
    await AppDataSource.query(
      `CREATE TABLE IF NOT EXISTS "migrations" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "timestamp" bigint NOT NULL,
        "name" character varying NOT NULL,
        CONSTRAINT "PK_migrations" PRIMARY KEY ("id")
      )`,
    );
    for (const m of ALREADY_APPLIED) {
      await AppDataSource.query(
        `INSERT INTO "migrations" ("timestamp", "name")
         SELECT $1, $2
         WHERE NOT EXISTS (SELECT 1 FROM "migrations" WHERE "name" = $2)`,
        [m.timestamp, m.name],
      );
    }
    console.log('baseline: migration history ready');
  } finally {
    await AppDataSource.destroy();
  }
}

baseline().catch((err) => {
  console.error(err);
  process.exit(1);
});
